customer_folder = "@ASSIGNED_FOLDER_ID@" 
primary_project = "@ASSIGNED_PROJECT_ID@"
customer_org_id = "@ORG@"
primary_zone = "@PRIMARY_ZONE@"
controller_machine_type = "n1-standard-8"
login_machine_type = "n1-standard-8"
