
steps:
- id: Terraform plan and apply
  name: 'hashicorp/terraform:0.14.7'
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
      cd active
      terraform init
      terraform validate || exit 1
      terraform plan || exit 1
      terraform apply -auto-approve

- id: Update cluster
  name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: "/bin/bash"
  args:
  - '-c'
  - |
      sleep 60
      ssh-keygen -b 2048 -t rsa -f /tmp/sshkey -q -N ""

      gcloud compute ssh oshackathon-slurm-controller --zone=us-west1-b \
                                                      --ssh-key-file=/tmp/sshkey \
                                                      --command="sudo -i /apps/cls/bin/cluster-services update config"

      for i in $(gcloud compute os-login ssh-keys list); do echo $i; gcloud compute os-login ssh-keys remove --key $i; done
