
steps:
- id: Terraform plan and apply
  name: 'hashicorp/terraform:0.14.7'
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
      cd active
      terraform init
      terraform validate || exit 1
      terraform plan || exit 1
      terraform apply -auto-approve

#- id: Restart the controller and login
#  name: 'gcr.io/cloud-builders/gcloud'
#  entrypoint: "/bin/bash"
#  args: ["tools/restart-instances.sh"]
