
steps:
- id: Terraform plan
  name: 'hashicorp/terraform:0.14.7'
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
      cd active
      terraform init
      terraform validate || exit 1
      terraform plan || exit 1
