steps:


- id: &BUILD Build Image
  name: 'hashicorp/packer:latest'
  args: ["build",
        "-force",
        "-var","project_id=$PROJECT_ID",
        "-var","zone=$_ZONE",
        "-var","source_image_family=${_SOURCE_IMAGE_FAMILY}",
        "-var","source_image_project=${_SOURCE_IMAGE_PROJECT}",
        "-var","subnet=${_SUBNETWORK}",
        "-var","image_name=${_IMAGE_FAMILY}-${SHORT_SHA}",
        "-var","image_family=${_IMAGE_FAMILY}",
        "-var","install_root=${_INSTALL_ROOT}",
        "-var","slurm_root=${_SLURM_ROOT}",
        "-var","compiler=${_COMPILER}",
        'img/packer.json']
  waitFor: ["-"]


substitutions:
    _ZONE: 'us-central1-c'
    _SUBNETWORK: 'default'
    _SOURCE_IMAGE_FAMILY: 'fluid-slurm-gcp-centos-7-v3'
    _SOURCE_IMAGE_PROJECT: 'fluid-cluster-ops'
    _IMAGE_FAMILY: 'oshackathon-slurm-gcp'
    _INSTALL_ROOT: '/opt'
    _SLURM_ROOT: '/usr/local'

timeout : 86400s
